import type { CorpusText } from "./types";

function x(
  slug: string,
  titleEn: string,
  titleLt: string,
  collection: CorpusText["collection"],
  provenance: string,
  tags: CorpusText["tags"],
): CorpusText {
  return {
    slug,
    titleEn,
    titleLt,
    collection,
    provenance,
    originalLanguage: "Greek / Coptic / Latin",
    discovery: "manuscript tradition",
    dateApprox: "2nd–5th c.",
    introEn: "Public-domain English from the AEON source corpus (Mattison, Zinner, James, ANF, Mead).",
    introLt: "Viešosios nuosavybės anglų tekstas iš AEON šaltinių korpuso (Mattison, Zinner, James, ANF, Mead).",
    chapters: [{ id: "1", titleEn: "Full text", titleLt: "Visas tekstas" }],
    tags,
    related: [],
    completeness: "full",
    license: "Public Domain",
  };
}

export const extraCorpus: CorpusText[] = [
  x("egerton", "Unknown Gospel (Egerton)", "Nežinoma evangelija (Egerton)", "fragments", "P.Egerton 2", ["sayings"]),
  x("gospel-q", "Gospel of Q", "Q evangelija", "nt-apocrypha", "reconstruction", ["sayings"]),
  x("poxy-5575", "Sayings of Jesus (P.Oxy. 5575)", "Jėzaus posakiai (P.Oxy. 5575)", "fragments", "P.Oxy. 5575", ["sayings"]),
  x("secret-mark", "Secret Gospel of Mark", "Slaptoji Morkaus evangelija", "nt-apocrypha", "Mar Saba letter", ["sayings"]),
  x("stranger-tchacos", "The Stranger’s Book", "Svetimojo knyga", "nt-apocrypha", "Codex Tchacos", ["revelation"]),
  x("melchizedek-2", "2 Melchizedek", "2 Melchizedekas", "nag-hammadi", "NHC IX?", ["revelation"]),
  x("apocalypse-paul", "Revelation of Paul (NHC)", "Pauliaus apreiškimas (NHC)", "nag-hammadi", "NHC V,2", ["ascent"]),
  x("testimony-truth", "Testimony of Truth", "Tiesos liudijimas", "nag-hammadi", "NHC IX,3", ["salvation"]),
  x("apelles", "Apelles", "Apelėjas", "patristic", "Mead", ["pleroma"]),
  x("valentinian-movement", "The Valentinian Movement", "Valentinianų sąjūdis", "patristic", "Mead 1900", ["pleroma"]),
  x("valentinus", "Valentinus", "Valentinas", "patristic", "Mead 1900", ["pleroma"]),
  x("james-fragments", "Fragments of Early Gospels", "Ankstyvųjų evangelijų fragmentai", "fragments", "James 1924", ["sayings"]),
  x("lost-heretical", "Lost Heretical Books", "Prarastos eretikų knygos", "fragments", "James 1924", ["revelation"]),
  x("against-marcion-1", "Against Marcion I", "Prieš Markioną I", "patristic", "ANF 1885", ["salvation"]),
  x("against-marcion-2", "Against Marcion II", "Prieš Markioną II", "patristic", "ANF 1885", ["salvation"]),
  x("against-marcion-3", "Against Marcion III", "Prieš Markioną III", "patristic", "ANF 1885", ["salvation"]),
  x("against-marcion-4", "Against Marcion IV", "Prieš Markioną IV", "patristic", "ANF 1885", ["salvation"]),
  x("against-marcion-5", "Against Marcion V", "Prieš Markioną V", "patristic", "ANF 1885", ["salvation"]),
  x("poxy-1224", "P.Oxy. 1224", "P.Oxy. 1224", "fragments", "Grenfell & Hunt", ["sayings"]),
  x("poxy-840", "P.Oxy. 840", "P.Oxy. 840", "fragments", "Grenfell & Hunt", ["sayings"]),
  x("melchizedek-qumran", "Melchizedek (11Q13)", "Melchizedekas (11Q13)", "fragments", "Qumran", ["revelation"]),
  x("odes-solomon", "Odes of Solomon", "Saliamono odės", "nt-apocrypha", "Syriac", ["salvation"]),
  x("untitled-bruce", "Untitled Text (Bruce)", "Bevardis tekstas (Bruce)", "askew-bruce", "Bruce Codex", ["pleroma"]),
  x("pseudo-matthew", "Gospel of Pseudo-Matthew", "Pseudo-Mato evangelija", "nt-apocrypha", "Latin infancy", ["infancy"]),
  x("arabic-infancy", "Arabic Infancy Gospel", "Arabiškoji vaikystės evangelija", "nt-apocrypha", "Arabic", ["infancy"]),
  x("joseph-carpenter", "History of Joseph the Carpenter", "Juozapo dailidės istorija", "nt-apocrypha", "Coptic/Arabic", ["infancy"]),
  x("bartholomew", "Questions of Bartholomew", "Baltramiejaus klausimai", "nt-apocrypha", "James 1924", ["revelation"]),
  x("fayyum", "Fayyum Gospel Fragment", "Fajumo fragmentas", "fragments", "papyrus", ["sayings"]),
  x("bartholomew-resurrection", "Book of the Resurrection (Bartholomew)", "Prisikėlimo knyga (Baltramiejus)", "nt-apocrypha", "Budge 1913", ["revelation"]),
  x("thomas-poxy-1", "Thomas Greek fragments (P.Oxy. 1)", "Tomo graikų fragmentai (P.Oxy. 1)", "fragments", "Grenfell & Hunt", ["sayings"]),
  x("thomas-poxy-654", "Thomas Greek fragments (P.Oxy. 654)", "Tomo graikų fragmentai (P.Oxy. 654)", "fragments", "Grenfell & Hunt", ["sayings"]),
  x("egyptians-patristic", "Gospel of the Egyptians (patristic)", "Egiptiečių evangelija (patristinė)", "fragments", "James 1924", ["sayings"]),
  x("hebrews", "Gospel of the Hebrews", "Hebrajų evangelija", "nt-apocrypha", "James 1924", ["sayings"]),
  x("apocalypse-peter-greek", "Apocalypse of Peter (Akhmim)", "Petro apokalipsė (Achmimas)", "nt-apocrypha", "James 1924", ["revelation"]),
  x("hermas", "Shepherd of Hermas", "Herma ganytojas", "nt-apocrypha", "Lightfoot", ["revelation"]),
  x("preaching-peter", "Preaching of Peter", "Petro skelbimas", "fragments", "James 1924", ["sayings"]),
  x("ebionites", "Gospel of the Ebionites", "Ebionitų evangelija", "fragments", "James 1924", ["sayings"]),
  x("matthias", "Traditions of Matthias", "Matijo tradicijos", "fragments", "James 1924", ["sayings"]),
  x("epistula-apostolorum", "Epistula Apostolorum", "Apaštalų laiškas", "nt-apocrypha", "James 1924", ["revelation"]),
  x("acts-peter", "Acts of Peter", "Petro aktai", "nt-apocrypha", "James 1924", ["salvation"]),
  x("acts-john", "Acts of John", "Jono aktai", "nt-apocrypha", "James 1924", ["salvation"]),
  x("acts-paul", "Acts of Paul", "Pauliaus aktai", "nt-apocrypha", "James 1924", ["salvation"]),
  x("3-corinthians", "Third Corinthians", "Trečiasis laiškas korintiečiams", "nt-apocrypha", "James 1924", ["salvation"]),
  x("acts-andrew", "Acts of Andrew", "Andriejaus aktai", "nt-apocrypha", "James 1924", ["salvation"]),
  x("acts-andrew-matthias", "Acts of Andrew and Matthias", "Andriejaus ir Matijo aktai", "nt-apocrypha", "ANF", ["salvation"]),
  x("acts-thomas", "Acts of Thomas", "Tomo aktai", "nt-apocrypha", "James 1924", ["ascent"]),
  x("acts-peter-paul", "Acts of Peter and Paul", "Petro ir Pauliaus aktai", "nt-apocrypha", "ANF", ["salvation"]),
  x("basilides", "Basilides", "Bazilidas", "patristic", "patristic fragments", ["pleroma"]),
  x("naassene", "Naassene Fragment", "Naasenų fragmentas", "patristic", "Hippolytus", ["pleroma"]),
  x("epiphanes", "Epiphanes, On Righteousness", "Epifanas, Apie teisumą", "patristic", "Clement", ["salvation"]),
  x("ptolemy-flora", "Ptolemy, Letter to Flora", "Ptolemėjo laiškas Florai", "patristic", "Epiphanius", ["pleroma"]),
  x("theodotus", "Excerpts of Theodotus", "Teodoto ištraukos", "patristic", "Clement", ["pleroma"]),
  x("heracleon", "Fragments of Heracleon", "Herakleono fragmentai", "patristic", "Origen", ["pleroma"]),
  x("marcion-gospel", "Marcion, Gospel of the Lord", "Markiono Viešpaties evangelija", "patristic", "reconstruction", ["salvation"]),
  x("visio-pauli", "Apocalypse of Paul (Visio Pauli)", "Pauliaus apokalipsė (Visio Pauli)", "nt-apocrypha", "James 1924", ["ascent"]),
  x("apocalypse-virgin", "Apocalypse of the Virgin", "Mergelės apokalipsė", "nt-apocrypha", "James 1924", ["revelation"]),
  x("apocalypse-thomas", "Apocalypse of Thomas", "Tomo apokalipsė", "nt-apocrypha", "James 1924", ["revelation"]),
  x("life-of-john", "Life of John the Baptist", "Jono Krikštytojo gyvenimas", "nt-apocrypha", "Mingana 1927", ["infancy"]),
  x("pilate-tiberius", "Letter of Pilate to Tiberius", "Piloto laiškas Tiberijui", "nt-apocrypha", "James 1924", ["revelation"]),
  x("giving-up-pilate", "Giving Up of Pontius Pilate", "Piloto atidavimas", "nt-apocrypha", "James 1924", ["revelation"]),
  x("death-pilate", "Death of Pilate", "Piloto mirtis", "nt-apocrypha", "James 1924", ["revelation"]),
  x("vindicta", "Avenging of the Saviour", "Išgelbėtojo kerštas", "nt-apocrypha", "James 1924", ["revelation"]),
  x("clementine-recognitions", "Clementine Recognitions", "Klementinų atpažinimai", "nt-apocrypha", "ANF", ["salvation"]),
  x("clementine-homilies", "Clementine Homilies", "Klementinų homilijos", "nt-apocrypha", "ANF", ["salvation"]),
  x("acts-philip", "Acts of Philip", "Pilypo aktai", "nt-apocrypha", "ANF", ["salvation"]),
  x("acts-barnabas", "Acts of Barnabas", "Barnabo aktai", "nt-apocrypha", "ANF", ["salvation"]),
  x("abgar", "Letters of Christ and Abgar", "Kristo ir Abgaro laiškai", "nt-apocrypha", "Eusebius HE I.13", ["revelation"]),
  x("laodiceans", "Epistle to the Laodiceans", "Laiškas laodikiečiams", "nt-apocrypha", "James 1924", ["salvation"]),
  x("paul-seneca", "Paul and Seneca", "Paulius ir Seneka", "nt-apocrypha", "James 1924", ["salvation"]),
];
