import { extraCorpus } from "./corpus-extra";
import manifest from "@/content/bodies/_manifest.json";
import metaLt from "@/content/meta-lt.json";
import type { Chapter, CollectionId, Completeness, CorpusText, ThemeTag } from "./types";

export const collections: Record<
  CollectionId,
  { titleLt: string; titleEn: string; blurbLt: string; blurbEn: string }
> = {
  "nag-hammadi": {
    titleLt: "Nag Hammadi",
    titleEn: "Nag Hammadi",
    blurbLt: "Kodeksai I–XIII, palaidoti apie IV a. ir rasti 1945 m. Aukštutiniame Egipte.",
    blurbEn: "Codices I–XIII, buried in the fourth century and found in 1945 in Upper Egypt.",
  },
  "berlin-codex": {
    titleLt: "Berlyno kodeksas",
    titleEn: "Berlin Codex",
    blurbLt: "Papyrus Berolinensis 8502 — Marija, trumpasis Jonas, Sofija, Petro aktas.",
    blurbEn: "Papyrus Berolinensis 8502 — Mary, short John, Sophia, Act of Peter.",
  },
  "nt-apocrypha": {
    titleLt: "Naujojo Testamento apokrifai",
    titleEn: "New Testament Apocrypha",
    blurbLt: "Evangelijos, aktai ir apokalipsės, kurių kanonas nepriėmė.",
    blurbEn: "Gospels, acts, and apocalypses the canon did not receive.",
  },
  "askew-bruce": {
    titleLt: "Askew ir Bruce",
    titleEn: "Askew & Bruce",
    blurbLt: "Koptų rinkiniai, žinomi iki Nag Hammadi: Pistis Sophia ir Jeu knygos.",
    blurbEn: "Coptic books known before Nag Hammadi: Pistis Sophia and the Books of Jeu.",
  },
  patristic: {
    titleLt: "Patristika ir mokyklos",
    titleEn: "Patristic & schools",
    blurbLt: "ANF ir Mead: Markionas, Valentinas, Ptolemėjas, Herakleonas — liudijimai, ne kanonas.",
    blurbEn: "ANF and Mead: Marcion, Valentinus, Ptolemy, Heracleon — witnesses, not a canon.",
  },
  fragments: {
    titleLt: "Fragmentai",
    titleEn: "Fragments",
    blurbLt: "Papirusai ir Jameso liudijimai: Egerton, Oksirinchas, prarastos knygos.",
    blurbEn: "Papyri and James’s testimonia: Egerton, Oxyrhynchus, lost books.",
  },
};

function ch(n: number | string, en: string, lt?: string): Chapter {
  return { id: String(n), titleEn: en, titleLt: lt ?? en };
}

function stubChapters(label = "Opening"): Chapter[] {
  return [ch(1, label, "Pradžia")];
}

function t(
  partial: Omit<CorpusText, "introLt"> & { introLt?: string },
): CorpusText {
  return {
    introLt: partial.introLt ?? partial.introEn,
    ...partial,
  };
}

const coreTexts: CorpusText[] = [
  t({
    slug: "thomas",
    titleEn: "Gospel of Thomas",
    titleLt: "Tomo evangelija",
    originalTitle: "Peua[n]gelion pkata Thomas",
    collection: "nag-hammadi",
    codex: "NHC II,2",
    provenance: "Nag Hammadi, Upper Egypt",
    originalLanguage: "Coptic (Sahidic), from Greek",
    discovery: "1945",
    dateApprox: "mid–late 2nd c.",
    introEn:
      "A collection of 114 sayings attributed to the living Jesus, without narrative passion. The Coptic text is from Codex II; Greek fragments were already known from Oxyrhynchus. The translation here is Mark M. Mattison’s public-domain rendering.",
    introLt:
      "114 posakių, priskiriamų gyvajam Jėzui, be kančios pasakojimo. Koptų tekstas — Kodeksas II; graikiški fragmentai jau buvo žinomi iš Oksirinho. Čia — Marko M. Mattisono viešosios nuosavybės vertimas.",
    chapters: Array.from({ length: 114 }, (_, i) =>
      ch(i + 1, `Saying ${i + 1}`, `Posakis ${i + 1}`),
    ),
    tags: ["sayings", "salvation"],
    related: ["philip", "mary", "secret-james", "infancy-thomas"],
    completeness: "full",
    translator: "Mark M. Mattison",
    sourceUrl: "https://www.gospels.net/thomas",
    license: "Public Domain",
    featured: true,
    bannedBadge: true,
  }),
  t({
    slug: "philip",
    titleEn: "Gospel of Philip",
    titleLt: "Pilypo evangelija",
    collection: "nag-hammadi",
    codex: "NHC II,3",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn:
      "A Valentinian anthology on names, sacraments, and the bridal chamber. Not a narrative gospel. Public-domain excerpts by Mark Mattison.",
    introLt:
      "Valentinianų rinkinys apie vardus, sakramentus ir vestuvių kambarį. Ne pasakojamoji evangelija.",
    chapters: [ch(1, "Gentiles and names", "Vardai"), ch(2, "The rulers", "Valdovai")],
    tags: ["ritual", "salvation", "sophia"],
    related: ["thomas", "truth", "valentinus-exposition"],
    completeness: "excerpt",
    translator: "Mark M. Mattison",
    sourceUrl: "https://www.gospels.net/philip",
    license: "Public Domain",
    featured: true,
  }),
  t({
    slug: "truth",
    titleEn: "Gospel of Truth",
    titleLt: "Tiesos evangelija",
    collection: "nag-hammadi",
    codex: "NHC I,3 / XII,2",
    provenance: "Jung Codex",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "mid-2nd c.",
    introEn:
      "A homiletic meditation, often linked to Valentinian circles, on Error, forgetfulness, and the Father’s knowledge. Mattison PD translation excerpts.",
    introLt:
      "Homilinė meditacija, siejama su valentinianais: Klaida, užmarštis ir Tėvo pažinimas. Mattisono PD ištraukos.",
    chapters: [ch(1, "Prologue", "Prologas"), ch(2, "Error", "Klaida")],
    tags: ["pleroma", "salvation", "sophia"],
    related: ["tripartite", "rheginos", "philip"],
    completeness: "excerpt",
    translator: "Mark M. Mattison",
    sourceUrl: "https://www.gospels.net/truth",
    license: "Public Domain",
    featured: true,
  }),
  t({
    slug: "egyptians-sethian",
    titleEn: "Gospel of the Egyptians (Sethian)",
    titleLt: "Egiptiečių evangelija (setianų)",
    originalTitle: "The Sacred Book of the Great Invisible Spirit",
    collection: "nag-hammadi",
    codex: "NHC III,2 / IV,2",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn:
      "Also called the Holy Book of the Great Invisible Spirit. A Sethian theogony and baptismal liturgy, distinct from the Greek Gospel of the Egyptians known only from patristic citations.",
    chapters: stubChapters(),
    tags: ["pleroma", "baptism", "archons"],
    related: ["john", "protennoia", "three-steles"],
    completeness: "stub",
  }),
  t({
    slug: "john",
    titleEn: "Apocryphon of John",
    titleLt: "Jono apokrifas",
    collection: "nag-hammadi",
    codex: "NHC II,1 / III,1 / IV,1 + BG 8502,2",
    provenance: "Nag Hammadi and Berlin",
    originalLanguage: "Coptic, from Greek",
    discovery: "1896 (BG) / 1945 (NHC)",
    dateApprox: "2nd c.",
    introEn:
      "The central Sethian revelation: Barbelo, the Autogenes, the fall of Sophia, and Yaldabaoth. Survives in a long recension (II, IV) and a short recension (III, BG).",
    introLt:
      "Pagrindinis setianų apreiškimas: Barbelo, Autogenes, Sofijos nuopuolis ir Yaldabaothas. Ilgoji (II, IV) ir trumpoji (III, BG) recenzijos.",
    chapters: [
      ch(1, "The frame", "Rėmas"),
      ch(2, "Barbelo", "Barbelo"),
      ch(3, "Yaldabaoth", "Yaldabaothas"),
    ],
    tags: ["sophia", "archons", "pleroma", "revelation"],
    related: ["archons", "origin", "sophia-jesus"],
    completeness: "stub",
  }),
  t({
    slug: "secret-james",
    titleEn: "Apocryphon of James",
    titleLt: "Jokūbo apokrifas",
    collection: "nag-hammadi",
    codex: "NHC I,2",
    provenance: "Jung Codex",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "2nd c.",
    introEn:
      "A post-resurrection dialogue of Jesus with James and Peter, framed as a secret letter.",
    chapters: stubChapters(),
    tags: ["sayings", "revelation", "salvation"],
    related: ["thomas", "1james", "epistula-apostolorum"],
    completeness: "stub",
  }),
  t({
    slug: "adam",
    titleEn: "Apocalypse of Adam",
    titleLt: "Adomo apokalipsė",
    collection: "nag-hammadi",
    codex: "NHC V,5",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "1st–4th c.",
    introEn:
      "Adam recounts to Seth a revelation about three descents of a savior figure and the survival of a Sethian seed.",
    chapters: stubChapters(),
    tags: ["revelation", "archons", "salvation"],
    related: ["john", "shem", "three-steles"],
    completeness: "stub",
  }),
  t({
    slug: "apocalypse-peter-nhc",
    titleEn: "Apocalypse of Peter (NHC VII)",
    titleLt: "Petro apokalipsė (NHC VII)",
    collection: "nag-hammadi",
    codex: "NHC VII,3",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn:
      "A Gnostic crucifixion apocalypse, not the Akhmim Apocalypse of Peter. The Savior interprets the apparent suffering as belonging to the fleshly substitute.",
    chapters: stubChapters(),
    tags: ["revelation", "salvation"],
    related: ["great-seth", "peter-philip"],
    completeness: "stub",
  }),
  t({
    slug: "1james",
    titleEn: "First Apocalypse of James",
    titleLt: "Pirmoji Jokūbo apokalipsė",
    collection: "nag-hammadi",
    codex: "NHC V,3 / CT 2",
    provenance: "Nag Hammadi; Codex Tchacos",
    originalLanguage: "Coptic",
    discovery: "1945 / 1970s",
    dateApprox: "2nd–3rd c.",
    introEn:
      "James receives passwords for the ascent past the archons. A second copy survives in Codex Tchacos.",
    chapters: stubChapters(),
    tags: ["ascent", "archons", "revelation"],
    related: ["2james", "secret-james"],
    completeness: "stub",
  }),
  t({
    slug: "2james",
    titleEn: "Second Apocalypse of James",
    titleLt: "Antroji Jokūbo apokalipsė",
    collection: "nag-hammadi",
    codex: "NHC V,4",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A discourse of James before his martyrdom, with a hymn-like confession.",
    chapters: stubChapters(),
    tags: ["revelation", "salvation"],
    related: ["1james", "secret-james"],
    completeness: "stub",
  }),
  t({
    slug: "archons",
    titleEn: "Hypostasis of the Archons",
    titleLt: "Archontų hipostazė",
    collection: "nag-hammadi",
    codex: "NHC II,4",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn:
      "A Sethian rewriting of Genesis: the rulers, Norea, and the Eleleth revelation.",
    chapters: stubChapters(),
    tags: ["archons", "sophia", "pleroma"],
    related: ["origin", "john", "norea"],
    completeness: "stub",
  }),
  t({
    slug: "origin",
    titleEn: "On the Origin of the World",
    titleLt: "Apie pasaulio kilmę",
    collection: "nag-hammadi",
    codex: "NHC II,5 / XIII,2",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd–4th c.",
    introEn: "A cosmological treatise overlapping the Hypostasis of the Archons.",
    chapters: stubChapters(),
    tags: ["archons", "sophia", "pleroma"],
    related: ["archons", "john"],
    completeness: "stub",
  }),
  t({
    slug: "thunder",
    titleEn: "Thunder, Perfect Mind",
    titleLt: "Griaustinis, tobula mintis",
    originalTitle: "Brontē",
    collection: "nag-hammadi",
    codex: "NHC VI,2",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn:
      "A riddling I-am discourse in a feminine voice. Public-domain translation by Samuel Zinner, edited by Mark Mattison.",
    introLt:
      "Mįslingas „aš esu“ diskursas moterišku balsu. Viešosios nuosavybės vertimas: Samuel Zinner, red. Mark Mattison.",
    chapters: [ch(1, "Introduction", "Įžanga"), ch(2, "I am", "Aš esu")],
    tags: ["sophia", "revelation", "pleroma"],
    related: ["protennoia", "norea", "truth"],
    completeness: "excerpt",
    translator: "Samuel Zinner / Mark Mattison",
    sourceUrl: "https://othergospels.com/thunder/",
    license: "Public Domain",
    featured: true,
  }),
  t({
    slug: "protennoia",
    titleEn: "Trimorphic Protennoia",
    titleLt: "Trimorfinė Protenoja",
    collection: "nag-hammadi",
    codex: "NHC XIII,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "Three descents of First Thought as Father, Mother, and Son / Logos.",
    chapters: stubChapters(),
    tags: ["sophia", "revelation", "pleroma"],
    related: ["thunder", "john"],
    completeness: "stub",
  }),
  t({
    slug: "norea",
    titleEn: "Thought of Norea",
    titleLt: "Noreos mintis",
    collection: "nag-hammadi",
    codex: "NHC IX,2",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A short hymnic address of Norea to the four holy helpers.",
    chapters: stubChapters(),
    tags: ["sophia", "pleroma"],
    related: ["archons", "thunder"],
    completeness: "stub",
  }),
  t({
    slug: "soul",
    titleEn: "Exegesis on the Soul",
    titleLt: "Sielos egzegezė",
    collection: "nag-hammadi",
    codex: "NHC II,6",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "An allegorical fall and restoration of the soul, stitched with scripture.",
    chapters: stubChapters(),
    tags: ["salvation", "sophia"],
    related: ["authoritative", "rheginos"],
    completeness: "stub",
  }),
  t({
    slug: "authoritative",
    titleEn: "Authoritative Teaching",
    titleLt: "Autoritetingas mokymas",
    collection: "nag-hammadi",
    codex: "NHC VI,3",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "The soul as a pearl among merchants; a non-Sethian wisdom homily.",
    chapters: stubChapters(),
    tags: ["salvation"],
    related: ["soul", "silvanus"],
    completeness: "stub",
  }),
  t({
    slug: "rheginos",
    titleEn: "Treatise on the Resurrection",
    titleLt: "Traktatas apie prisikėlimą",
    originalTitle: "To Rheginos",
    collection: "nag-hammadi",
    codex: "NHC I,4",
    provenance: "Jung Codex",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "late 2nd c.",
    introEn: "A Valentinian letter arguing that resurrection is already spiritual reality.",
    chapters: stubChapters(),
    tags: ["salvation", "pleroma"],
    related: ["truth", "tripartite"],
    completeness: "stub",
  }),
  t({
    slug: "tripartite",
    titleEn: "Tripartite Tractate",
    titleLt: "Trišalis traktatas",
    collection: "nag-hammadi",
    codex: "NHC I,5",
    provenance: "Jung Codex",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn:
      "The longest Valentinian systematic treatise: Father, Son, Church; the Logos; three kinds of humanity.",
    chapters: stubChapters("The Father"),
    tags: ["pleroma", "sophia", "salvation"],
    related: ["truth", "valentinus-exposition"],
    completeness: "stub",
  }),
  t({
    slug: "valentinus-exposition",
    titleEn: "Valentinian Exposition",
    titleLt: "Valentinian ekspozicija",
    collection: "nag-hammadi",
    codex: "NHC XI,2",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn:
      "A fragmentary Valentinian cosmogony followed by liturgical readings on anointing, baptism, and eucharist.",
    chapters: stubChapters(),
    tags: ["pleroma", "ritual", "baptism"],
    related: ["valentinus-liturgy", "tripartite"],
    completeness: "stub",
  }),
  t({
    slug: "mary",
    titleEn: "Gospel of Mary",
    titleLt: "Marijos evangelija",
    collection: "berlin-codex",
    codex: "BG 8502,1 (+ P.Oxy. 3525, P.Ryl. 463)",
    provenance: "Berlin Codex; Greek fragments",
    originalLanguage: "Coptic and Greek",
    discovery: "1896",
    dateApprox: "2nd c.",
    introEn:
      "Mary recounts a vision of the soul’s ascent past Desire, Ignorance, and Wrath. Pages 1–6 and 11–14 are lost. Mattison PD translation excerpts.",
    introLt:
      "Marija pasakoja sielos kilimą pro Geismą, Nežinojimą ir Rūstybę. Trūksta p. 1–6 ir 11–14. Mattisono PD ištraukos.",
    chapters: [
      ch(1, "An eternal perspective", "Amžina perspektyva"),
      ch(2, "Mary and Jesus", "Marija ir Jėzus"),
      ch(3, "The powers", "Galios"),
    ],
    tags: ["ascent", "revelation", "salvation"],
    related: ["thomas", "judas", "dialogue-savior"],
    completeness: "excerpt",
    translator: "Mark M. Mattison",
    sourceUrl: "https://www.gospels.net/mary",
    license: "Public Domain",
    featured: true,
    bannedBadge: true,
  }),
  t({
    slug: "sophia-jesus",
    titleEn: "Sophia of Jesus Christ",
    titleLt: "Jėzaus Kristaus Sofija",
    collection: "nag-hammadi",
    codex: "NHC III,4 / BG 8502,3",
    provenance: "Nag Hammadi and Berlin",
    originalLanguage: "Coptic",
    discovery: "1896 / 1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A Christian dialogue recasting Eugnostos as a post-resurrection teaching.",
    chapters: stubChapters(),
    tags: ["sophia", "pleroma", "revelation"],
    related: ["eugnostos", "john"],
    completeness: "stub",
  }),
  t({
    slug: "dialogue-savior",
    titleEn: "Dialogue of the Savior",
    titleLt: "Išganytojo dialogas",
    collection: "nag-hammadi",
    codex: "NHC III,5",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd c.",
    introEn: "A fragmentary dialogue with Matthew, Judas, and Mary on rest and dissolution.",
    chapters: stubChapters(),
    tags: ["sayings", "salvation"],
    related: ["mary", "thomas"],
    completeness: "stub",
  }),
  t({
    slug: "contender",
    titleEn: "Book of Thomas the Contender",
    titleLt: "Tomo Kovotojo knyga",
    collection: "nag-hammadi",
    codex: "NHC II,7",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn: "An ascetic dialogue between the Savior and Judas Thomas on the body.",
    chapters: stubChapters(),
    tags: ["sayings", "salvation"],
    related: ["thomas", "secret-james"],
    completeness: "stub",
  }),
  t({
    slug: "peter-twelve",
    titleEn: "Acts of Peter and the Twelve Apostles",
    titleLt: "Petro ir dvylikos aktas",
    collection: "nag-hammadi",
    codex: "NHC VI,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "An allegorical voyage to the city of nine gates and the pearl merchant Lithargoel.",
    chapters: stubChapters(),
    tags: ["salvation"],
    related: ["act-peter", "peter-philip"],
    completeness: "stub",
  }),
  t({
    slug: "peter-philip",
    titleEn: "Letter of Peter to Philip",
    titleLt: "Petro laiškas Pilypui",
    collection: "nag-hammadi",
    codex: "NHC VIII,2 / CT 1",
    provenance: "Nag Hammadi; Tchacos",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "The apostles gather on the Mount of Olives; a revelation on deficiency and the archons.",
    chapters: stubChapters(),
    tags: ["archons", "revelation"],
    related: ["philip", "1james"],
    completeness: "stub",
  }),
  t({
    slug: "melchizedek",
    titleEn: "Melchizedek",
    titleLt: "Melchizedekas",
    collection: "nag-hammadi",
    codex: "NHC IX,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A badly damaged Sethian tractate identifying Melchizedek with a high-priestly Jesus.",
    chapters: stubChapters(),
    tags: ["revelation", "ritual"],
    related: ["john", "protennoia"],
    completeness: "stub",
  }),
  t({
    slug: "marsanes",
    titleEn: "Marsanes",
    titleLt: "Marsanes",
    collection: "nag-hammadi",
    codex: "NHC X",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd–4th c.",
    introEn: "A fragmentary Platonizing Sethian ascent treatise; most pages are badly damaged.",
    chapters: stubChapters(),
    tags: ["ascent", "pleroma"],
    related: ["allogenes", "zostrianos"],
    completeness: "stub",
  }),
  t({
    slug: "allogenes",
    titleEn: "Allogenes",
    titleLt: "Allogenes / Svetimasis",
    collection: "nag-hammadi",
    codex: "NHC XI,3",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn:
      "A Platonizing Sethian ascent. Distinct from the Tchacos Book of the Stranger.",
    chapters: stubChapters(),
    tags: ["ascent", "pleroma"],
    related: ["zostrianos", "marsanes"],
    completeness: "stub",
  }),
  t({
    slug: "zostrianos",
    titleEn: "Zostrianos",
    titleLt: "Zostrianos",
    collection: "nag-hammadi",
    codex: "NHC VIII,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn: "The longest Nag Hammadi tractate; a visionary ascent with many lacunae.",
    chapters: stubChapters(),
    tags: ["ascent", "pleroma"],
    related: ["allogenes", "three-steles"],
    completeness: "stub",
  }),
  t({
    slug: "three-steles",
    titleEn: "Three Steles of Seth",
    titleLt: "Trys Seto stelos",
    collection: "nag-hammadi",
    codex: "NHC VII,5",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn: "Three liturgical hymns of Dositheos to the Sethian triad.",
    chapters: stubChapters(),
    tags: ["ritual", "pleroma"],
    related: ["zostrianos", "allogenes"],
    completeness: "stub",
  }),
  t({
    slug: "hypsiphrone",
    titleEn: "Hypsiphrone",
    titleLt: "Hypsiphrone",
    collection: "nag-hammadi",
    codex: "NHC XI,4",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn: "Barely two leaves survive of a revelation by Hypsiphrone, ‘She of high thought’.",
    chapters: stubChapters(),
    tags: ["revelation"],
    related: ["norea"],
    completeness: "stub",
  }),
  t({
    slug: "sextus",
    titleEn: "Sentences of Sextus",
    titleLt: "Siksto sakiniai",
    collection: "nag-hammadi",
    codex: "NHC XII,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "2nd c. (Greek)",
    introEn: "A Christianized Pythagorean wisdom collection; not uniquely Gnostic.",
    chapters: stubChapters(),
    tags: ["sayings"],
    related: ["silvanus"],
    completeness: "stub",
  }),
  t({
    slug: "silvanus",
    titleEn: "Teachings of Silvanus",
    titleLt: "Silvano mokymai",
    collection: "nag-hammadi",
    codex: "NHC VII,4",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "Wisdom instruction closer to Alexandrian Christianity than to Sethian myth.",
    chapters: stubChapters(),
    tags: ["salvation"],
    related: ["sextus", "authoritative"],
    completeness: "stub",
  }),
  t({
    slug: "plato-republic",
    titleEn: "Plato, Republic 588b–589b",
    titleLt: "Platono Valstybė 588b–589b",
    collection: "nag-hammadi",
    codex: "NHC VI,5",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "copy 4th c.",
    introEn: "A poor Coptic rendering of the Republic’s image of the inner beasts.",
    chapters: stubChapters(),
    tags: ["ascent"],
    related: ["marsanes"],
    completeness: "stub",
  }),
  t({
    slug: "prayer-paul",
    titleEn: "Prayer of the Apostle Paul",
    titleLt: "Apaštalo Pauliaus malda",
    collection: "nag-hammadi",
    codex: "NHC I,1",
    provenance: "Jung Codex flyleaf",
    originalLanguage: "Coptic, from Greek",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A short invocation written on the front flyleaf of Codex I.",
    chapters: stubChapters(),
    tags: ["ritual", "pleroma"],
    related: ["thanksgiving", "truth"],
    completeness: "stub",
  }),
  t({
    slug: "thanksgiving",
    titleEn: "Prayer of Thanksgiving",
    titleLt: "Padėkos malda",
    collection: "nag-hammadi",
    codex: "NHC VI,7",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek (Hermetic)",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A Hermetic thanksgiving also known from Latin and Greek parallels.",
    chapters: stubChapters(),
    tags: ["ritual"],
    related: ["eighth-ninth", "asclepius"],
    completeness: "stub",
  }),
  t({
    slug: "eighth-ninth",
    titleEn: "Discourse on the Eighth and Ninth",
    titleLt: "Diskursas apie aštuntą ir devintą",
    collection: "nag-hammadi",
    codex: "NHC VI,6",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek (Hermetic)",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A Hermetic initiation into the Ogdoad and Ennead.",
    chapters: stubChapters(),
    tags: ["ascent", "ritual", "pleroma"],
    related: ["thanksgiving", "asclepius"],
    completeness: "stub",
  }),
  t({
    slug: "asclepius",
    titleEn: "Asclepius 21–29",
    titleLt: "Asklepijas 21–29",
    collection: "nag-hammadi",
    codex: "NHC VI,8",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic, from Greek (Hermetic)",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A Coptic excerpt of the Perfect Discourse, including the apocalypse of Egypt.",
    chapters: stubChapters(),
    tags: ["revelation"],
    related: ["eighth-ninth"],
    completeness: "stub",
  }),
  t({
    slug: "eugnostos",
    titleEn: "Eugnostos the Blessed",
    titleLt: "Palaimintasis Eugnostas",
    collection: "nag-hammadi",
    codex: "NHC III,3 / V,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "1st–2nd c.",
    introEn: "A non-Christian (or barely Christian) letter on the ineffable God and the aeons.",
    chapters: stubChapters(),
    tags: ["pleroma", "sophia"],
    related: ["sophia-jesus"],
    completeness: "stub",
  }),
  t({
    slug: "interpretation-knowledge",
    titleEn: "Interpretation of Knowledge",
    titleLt: "Žinių aiškinimas",
    collection: "nag-hammadi",
    codex: "NHC XI,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A fragmentary Valentinian homily on the church as one body.",
    chapters: stubChapters(),
    tags: ["salvation", "pleroma"],
    related: ["valentinus-exposition"],
    completeness: "stub",
  }),
  t({
    slug: "valentinus-liturgy",
    titleEn: "On the Anointing, Baptism, and Eucharist",
    titleLt: "Patepimas, krikštas, Eucharistija",
    collection: "nag-hammadi",
    codex: "NHC XI,2a–e",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "Liturgical fragments appended to the Valentinian Exposition.",
    chapters: [
      ch(1, "Anointing", "Patepimas"),
      ch(2, "Baptism", "Krikštas"),
      ch(3, "Eucharist", "Eucharistija"),
    ],
    tags: ["ritual", "baptism"],
    related: ["valentinus-exposition"],
    completeness: "stub",
  }),
  t({
    slug: "judas",
    titleEn: "Gospel of Judas",
    titleLt: "Judo evangelija",
    collection: "nt-apocrypha",
    codex: "Codex Tchacos 3",
    provenance: "Codex Tchacos",
    originalLanguage: "Coptic, from Greek",
    discovery: "1970s; published 2006",
    dateApprox: "2nd c.",
    introEn:
      "Jesus laughs at the disciples’ worship and takes Judas aside to speak of Barbelo. Mattison PD excerpts.",
    introLt:
      "Jėzus juokiasi iš mokinių garbinimo ir atitraukia Judą kalbėti apie Barbelo. Mattisono PD ištraukos.",
    chapters: [
      ch(1, "Introduction", "Įžanga"),
      ch(2, "The disciples", "Mokiniai"),
    ],
    tags: ["revelation", "archons", "pleroma"],
    related: ["john", "mary", "thomas"],
    completeness: "excerpt",
    translator: "Mark M. Mattison",
    sourceUrl: "https://www.gospels.net/judas",
    license: "Public Domain",
    featured: true,
    bannedBadge: true,
  }),
  t({
    slug: "infancy-thomas",
    titleEn: "Infancy Gospel of Thomas",
    titleLt: "Tomo vaikystės evangelija",
    collection: "nt-apocrypha",
    provenance: "Greek, Latin, Syriac recensions",
    originalLanguage: "Greek",
    discovery: "manuscript tradition",
    dateApprox: "2nd c.",
    introEn: "Childhood wonders of Jesus; distinct from the Nag Hammadi Gospel of Thomas.",
    chapters: stubChapters(),
    tags: ["infancy"],
    related: ["james-infancy", "thomas"],
    completeness: "stub",
  }),
  t({
    slug: "james-infancy",
    titleEn: "Protoevangelium of James",
    titleLt: "Jokūbo protoevangelija",
    collection: "nt-apocrypha",
    provenance: "Greek manuscript tradition",
    originalLanguage: "Greek",
    discovery: "manuscript tradition",
    dateApprox: "late 2nd c.",
    introEn: "Mary’s birth, childhood, and the nativity; hugely influential in later piety.",
    chapters: stubChapters(),
    tags: ["infancy"],
    related: ["infancy-thomas", "nicodemus"],
    completeness: "stub",
  }),
  t({
    slug: "peter-gospel",
    titleEn: "Gospel of Peter",
    titleLt: "Petro evangelija",
    collection: "nt-apocrypha",
    provenance: "Akhmim fragment; P.Oxy. fragments",
    originalLanguage: "Greek",
    discovery: "1886–87",
    dateApprox: "2nd c.",
    introEn: "A passion and empty-tomb narrative with a walking, talking cross.",
    chapters: stubChapters(),
    tags: ["revelation"],
    related: ["nicodemus", "apocalypse-peter-nhc"],
    completeness: "stub",
  }),
  t({
    slug: "nicodemus",
    titleEn: "Gospel of Nicodemus / Acts of Pilate",
    titleLt: "Nikodemo evangelija",
    collection: "nt-apocrypha",
    provenance: "Greek and Latin recensions",
    originalLanguage: "Greek / Latin",
    discovery: "manuscript tradition",
    dateApprox: "4th–5th c. (core earlier)",
    introEn: "Pilate’s court record and the Descent into Hell; parent of the medieval Pilate cycle.",
    chapters: stubChapters(),
    tags: ["revelation"],
    related: ["peter-gospel"],
    completeness: "stub",
  }),
  t({
    slug: "pistis-sophia",
    titleEn: "Pistis Sophia",
    titleLt: "Pistis Sophia",
    collection: "askew-bruce",
    codex: "Askew Codex",
    provenance: "Askew Codex (British Library)",
    originalLanguage: "Coptic",
    discovery: "acquired 18th c.; pub. 1851",
    dateApprox: "3rd–4th c.",
    introEn:
      "A long post-resurrection dialogue: Sophia’s fall and songs of repentance. Mead 1921 is public domain; this entry is structured by books.",
    chapters: [
      ch(1, "Book 1", "I knyga"),
      ch(2, "Book 2", "II knyga"),
      ch(3, "Book 3", "III knyga"),
      ch(4, "Book 4", "IV knyga"),
    ],
    tags: ["sophia", "ascent", "pleroma"],
    related: ["books-of-jeu", "thunder"],
    completeness: "stub",
  }),
  t({
    slug: "books-of-jeu",
    titleEn: "Books of Jeu",
    titleLt: "Jeu knygos",
    collection: "askew-bruce",
    codex: "Bruce Codex",
    provenance: "Bruce Codex (Bodleian)",
    originalLanguage: "Coptic",
    discovery: "1769; pub. 1891–92",
    dateApprox: "3rd–4th c.",
    introEn:
      "Two ritual books of diagrams and passwords. No complete public-domain English translation is available (MacDermot 1978 remains in copyright). This is a scholarly stub only.",
    introLt:
      "Dvi ritualinės knygos su diagramomis. Pilno PD angliško vertimo nėra (MacDermot 1978 saugomas). Tik stubas.",
    chapters: stubChapters(),
    tags: ["ritual", "ascent"],
    related: ["pistis-sophia"],
    completeness: "stub",
    bannedBadge: true,
  }),
  t({
    slug: "great-seth",
    titleEn: "Second Treatise of the Great Seth",
    titleLt: "Antroji Didžiojo Seto traktatas",
    collection: "nag-hammadi",
    codex: "NHC VII,2",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "3rd c.",
    introEn: "A revelatory sermon: the archons crucified a substitute; the living Jesus laughs.",
    chapters: stubChapters(),
    tags: ["archons", "revelation", "salvation"],
    related: ["apocalypse-peter-nhc", "john"],
    completeness: "stub",
  }),
  t({
    slug: "great-power",
    titleEn: "Concept of Our Great Power",
    titleLt: "Mūsų didžiosios galios samprata",
    collection: "nag-hammadi",
    codex: "NHC VI,4",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "4th c.",
    introEn: "A brief salvation-history in three ages, ending in a conflagration of the archons.",
    chapters: stubChapters(),
    tags: ["archons", "salvation", "revelation"],
    related: ["great-seth"],
    completeness: "stub",
  }),
  t({
    slug: "shem",
    titleEn: "Paraphrase of Shem",
    titleLt: "Šemo parafrazė",
    collection: "nag-hammadi",
    codex: "NHC VII,1",
    provenance: "Nag Hammadi",
    originalLanguage: "Coptic",
    discovery: "1945",
    dateApprox: "2nd–3rd c.",
    introEn: "A lengthy cosmogony of Light, Darkness, and Spirit, framed as Derdekeas to Shem.",
    chapters: stubChapters(),
    tags: ["archons", "pleroma", "revelation"],
    related: ["adam", "origin"],
    completeness: "stub",
  }),
  t({
    slug: "act-peter",
    titleEn: "Act of Peter (BG)",
    titleLt: "Petro aktas (Berlynas)",
    collection: "berlin-codex",
    codex: "BG 8502,4",
    provenance: "Berlin Codex",
    originalLanguage: "Coptic",
    discovery: "1896",
    dateApprox: "2nd–4th c.",
    introEn: "Peter heals, then un-heals, his paralyzed daughter. Not the NHC Acts of Peter and the Twelve.",
    chapters: stubChapters(),
    tags: ["salvation"],
    related: ["peter-twelve", "mary"],
    completeness: "stub",
  }),
];

const overlay = new Map(
  (manifest as Array<{ slug: string; completeness: Completeness; chapters: Chapter[] }>).map(
    (item) => [item.slug, item],
  ),
);

type MetaLt = Record<string, { titleLt?: string; introLt?: string; chapters?: Record<string, string> }>;
const meta = metaLt as MetaLt;

function applyMeta(item: CorpusText): CorpusText {
  const local = meta[item.slug];
  if (!local) return item;
  return {
    ...item,
    titleLt: local.titleLt && local.titleLt !== item.titleEn ? local.titleLt : item.titleLt,
    introLt: local.introLt && local.introLt !== item.introEn ? local.introLt : item.introLt,
    chapters: item.chapters.map((chapter) => ({
      ...chapter,
      titleLt: local.chapters?.[chapter.id] ?? chapter.titleLt,
    })),
  };
}

export const corpus: CorpusText[] = [...coreTexts, ...extraCorpus].map((item) => {
  const extra = overlay.get(item.slug);
  if (!extra) return applyMeta(item);
  return applyMeta({
    ...item,
    completeness: extra.completeness,
    chapters:
      item.slug === "thomas"
        ? item.chapters
        : extra.chapters.length > 16
          ? [{ id: "1", titleEn: "Full text", titleLt: "Visas tekstas" }]
          : extra.chapters,
    translator: item.translator,
    license: item.license ?? "Viešoji nuosavybė",
  });
});

export function collectionLabel(id: CollectionId, locale: "lt" | "en") {
  return locale === "lt" ? collections[id].titleLt : collections[id].titleEn;
}

export function licenseLabel(license: string | undefined, locale: "lt" | "en") {
  const value = license ?? (locale === "lt" ? "Viešoji nuosavybė" : "Public Domain");
  if (locale === "en") return value;
  if (/public domain/i.test(value) && /dedication/i.test(value)) {
    return "Viešoji nuosavybė (vertėjo dovana)";
  }
  if (/public domain/i.test(value)) return "Viešoji nuosavybė";
  return value;
}

export function getText(slug: string) {
  return corpus.find((item) => item.slug === slug);
}

export function textsByCollection(id: CollectionId) {
  return corpus.filter((item) => item.collection === id);
}

export function featuredTexts() {
  return corpus.filter((item) => item.featured);
}

export function relatedTexts(slug: string) {
  const item = getText(slug);
  if (!item) return [];
  return item.related.map(getText).filter(Boolean) as CorpusText[];
}

export const themeLabels: Record<ThemeTag, { lt: string; en: string }> = {
  sophia: { lt: "Sofija", en: "Sophia" },
  archons: { lt: "Archontai", en: "Archons" },
  salvation: { lt: "Išganymas", en: "Salvation" },
  baptism: { lt: "Krikštas", en: "Baptism" },
  pleroma: { lt: "Pleroma", en: "Pleroma" },
  revelation: { lt: "Apreiškimas", en: "Revelation" },
  sayings: { lt: "Posakiai", en: "Sayings" },
  infancy: { lt: "Vaikystė", en: "Infancy" },
  ritual: { lt: "Ritualas", en: "Ritual" },
  ascent: { lt: "Kilimas", en: "Ascent" },
};
